_wandb:
    value:
        cli_version: 0.23.1
        e:
            bnaa3ynraijeeauvb6vs4dcwawhylfkv:
                codePath: train_baseline_fish.py
                codePathLocal: train_baseline_fish.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "2000381014016"
                        used: "1405049368576"
                email: orisin@post.bgu.ac.il
                executable: D:\Projects\Practical_Deep_hw1\.venv\Scripts\python.exe
                git:
                    commit: 9f5d99ee0a74d61e85fda3b3b50dfff531bd0f63
                    remote: https://github.com/orimood/Practical_Deep_hw1.git
                gpu: NVIDIA GeForce RTX 2080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2944
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2080
                      uuid: GPU-e8f72c14-b206-0d4c-ac2f-dc846cbfaa30
                host: orimood-pc
                memory:
                    total: "68558614528"
                os: Windows-10-10.0.26200-SP0
                program: d:\Projects\Practical_Deep_hw1\train_baseline_fish.py
                python: CPython 3.10.7
                root: D:\Projects\Practical_Deep_hw1
                startedAt: "2025-12-04T11:06:49.046202Z"
                writerId: bnaa3ynraijeeauvb6vs4dcwawhylfkv
        m: []
        python_version: 3.10.7
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
                - 16
                - 17
            "4": 3.10.7
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 15
image_size:
    value: 224
learning_rate:
    value: 0.001
num_folds:
    value: 5
patience:
    value: 3
seed:
    value: 42
